// src/staffData.js

const staffData = [

  {
    id: 1,
    name: "Prof. Jyotsna Singh",
    role: "ECE, Director, IQAC",
    department: "ECE",
    position: "Director, IQAC",
    // photo: "/faculty/default-faculty.jpg", 
    linkedin: "#",
    googlescholar: "#",
  },
  {
    id: 2,
    name: "Dr. Jyoti Yadav",
    role: "ICE, Dy. Director, IQAC",
    department: "ICE",
    position: "Dy. Director, IQAC",
    // photo: "/faculty/default-faculty.jpg",
    linkedin: "#",
    googlescholar: "#",
  },
  {
    id: 3,
    name: "Dr. Akhlesh Dubey",
    role: "BT, Coordinator",
    department: "BT",
    position: "Coordinator",
    // photo: "/faculty/default-faculty.jpg",
    linkedin: "#",
    googlescholar: "#",
  },
  {
    id: 4,
    name: "Dr. Salini Roshine",
    role: "DMS, Coordinator",
    department: "DMS",
    position: "Coordinator",
    // photo: "/faculty/default-faculty.jpg",
    linkedin: "#",
    googlescholar: "#",
  },
  {
    id: 5,
    name: "Dr. Alok Agarwal",
    role: "ICE, Coordinator",
    department: "ICE",
    position: "Coordinator",
    // photo: "/faculty/default-faculty.jpg",
    linkedin: "#",
    googlescholar: "#",
  },
  {
    id: 6,
    name: "Dr. Mohit Sangwan",
    role: "IT, Coordinator",
    department: "IT",
    position: "Coordinator",
    // photo: "/faculty/default-faculty.jpg",
    linkedin: "#",
    googlescholar: "#",
  },
  {
    id: 7,
    name: "Dr. Amit Singhal",
    role: "ECE, Dy. Coordinator",
    department: "ECE",
    position: "Dy. Coordinator",
    // photo: "/faculty/default-faculty.jpg",
    linkedin: "#",
    googlescholar: "#",
  },
  {
    id: 8,
    name: "Dr. Geetanjali",
    role: "CSE, Dy. Coordinator",
    department: "CSE",
    position: "Dy. Coordinator",
    // photo: "/faculty/default-faculty.jpg",
    linkedin: "#",
    googlescholar: "#",
  },
  {
    id: 9,
    name: "Dr. Patteti Krishna",
    role: "ECE (East Campus), Dy. Coordinator",
    department: "ECE",
    position: "Dy. Coordinator (East Campus)",
    // photo: "/faculty/default-faculty.jpg",
    linkedin: "#",
    googlescholar: "#",
  },
  {
    id: 10,
    name: "Dr. Mahfuzuar Rahman Barbhuiya",
    role: "ARCH. (West Campus), Dy. Coordinator",
    department: "ARCH",
    position: "Dy. Coordinator (West Campus)",
    // photo: "/faculty/default-faculty.jpg",
    linkedin: "#",
    googlescholar: "#",
  },
];

export default staffData;

